import type { TErrors } from '../types/errors';

export const errors: TErrors = {
  networkError: 'خطأ في الشبكة. يرجى المحاولة مرة أخرى.',
  invalidContext: 'يرجى تقديم معلومات تتعلق بطلب الدعم الاجتماعي الخاص بك.',
  classificationError: 'تعذر معالجة مدخلاتك. يرجى المحاولة مرة أخرى.',
  submissionError: 'حدث خطأ أثناء إرسال طلبك. يرجى المحاولة لاحقًا.',
  parserError: 'فشل في تحليل بيانات النموذج المحفوظة.',
  somethingWentWrong: 'حدث خطأ ما.',
  noFound: 'لم يتم العثور على الصفحة.',
  error401: {
    code: 401,
    title: 'غير مصرح لك',
    message:
      'أنت غير مصرح لك بالوصول إلى هذه المورد. يرجى تسجيل الدخول أو التحقق من بياناتك.',
  },
  error404: {
    code: 404,
    title: 'لم يتم العثور على الصفحة',
    message:
      'قد تم إزالة المورد الذي تبحث عنه ، أو تغير اسمه ، أو لا يكون متاحًا للوصول حاليًا.',
  },
  error500: {
    code: 500,
    title: 'خطأ في الخادم',
    message:
      'حدث خطأ على الخادم. نحن نعمل على حل هذه المشكلة. يرجى المحاولة لاحقًا.',
  },
  error400: {
    code: 400,
    title: 'طلب غير صالح',
    message:
      'الطلب الذي قمت بإرساله كان غير صالح أو مشكل. يرجى التحقق من إدخالك والمحاولة مرة أخرى.',
  },
};
